### ISSUE TITLE
Individual Image Download

### ISSUE THREAD

**Issue by ZachKeskinen** [SnowEx/uavsar_pytools#1]
Let me know if this is the wrong format to open up an issue and assign it. Just trying this out.

Start simple with a single function to download an image from either JPL or ASF using a URL. Then we can wrap this functionality to bulk download or implement Paul's geo-searching algorithm.

Inputs: 
1. URL to an ASF or JPL file
2. Output Directory/ output filepath

Optional inputs:
1. Polarizations (other just give all in the zip file - usually VV, VH, HV, HH)
2. Specific file type (unw, amp1, amp2, coh, grd)

Code:
1. checks for ASF vs JPL
2. checks for polsar vs InSAR type
3. checks for existence of URL
4. Checks for netrc file or asks for ASF/JPL username and password
4. downloads URL contents (python requests or WGET?) with TQDM progress bar?

Returns
1. Errors

Code Sources:
https://github.com/SnowEx/snowexsql/blob/master/scripts/download/download_uavsar.py
https://github.com/ZachKeskinen/uavsar/blob/main/src/download-uavsar.py
https://github.com/jacktarricone/uavsar_scripts/blob/main/uavsar-download.ipynb

**Comment by micahjohnson150** [comment]
When you do commits you can link them here too. So in your commit message you can say `working on #1` and it will hyperlink automatically and show up here.
